import Providers from "@/providers/Providers";
import "./globals.css";

export const metadata = {
  title: "Tele Maktab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
